### ISSUE TITLE
Enhancement Request: Improve Settings Page UI

### ISSUE THREAD

**Issue by NamanAg0502** [NamanAg0502/pixelwant-frontend#2]
## Description
The current Settings page UI could benefit from some enhancements to improve user experience and make it more visually appealing.

## Proposed Changes
- [ ] Redesign the layout and structure of the Settings page to make it more intuitive.
- [ ] Update the color scheme and typography for better readability.

## Additional Information
Use [Mantine](https://mantine.dev) for pre-build react components

## Tasks
- [ ] Redesign the Settings page layout.
- [ ] Update color scheme and typography.
- [ ] Implement responsive design.

## Milestone
Milestone 3: Development Phase (End Date: October 30, 2023)

## Comments
- Use best practices while coding.
- Make reusable components, wherever applicable.

## Backend Repo
```
https://github.com/NamanAg0502/pixelwand-backend.git
```

**Comment by thesohailjafri** [comment]
Hii @NamanAg0502 I would like to Improve the setting page UI of pixelwant, I cloned the frontend and backend repos on my machine. I see you using next in frontend and node in the backend and I'm very proficient in that stack.

So I would request you to please assign this issue to me

Regards

**Comment by NamanAg0502** [comment]
Great and please follow the current code format
